"""Remove unused columns from posts

Revision ID: 035fbbe052a7
Revises: c5d4e3f2a1b0
Create Date: 2026-07-09 13:59:03.517950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '035fbbe052a7'
down_revision: Union[str, Sequence[str], None] = 'c5d4e3f2a1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'upvotes')
    op.drop_column('posts', 'ai_prompt_used')
    op.drop_column('posts', 'bg_video_used')
    op.drop_column('posts', 'author')
    op.drop_column('posts', 'ai_text')
    op.drop_column('posts', 'original_text')
    op.drop_column('posts', 'voice_used')
    op.drop_column('posts', 'music_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('music_used', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('posts', sa.Column('voice_used', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('posts', sa.Column('original_text', mysql.TEXT(), nullable=False))
    op.add_column('posts', sa.Column('ai_text', mysql.TEXT(), nullable=True))
    op.add_column('posts', sa.Column('author', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('posts', sa.Column('bg_video_used', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('posts', sa.Column('ai_prompt_used', mysql.TEXT(), nullable=True))
    op.add_column('posts', sa.Column('upvotes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
