"""Admin panel db architecture

Revision ID: 14cbbdc5343a
Revises: 
Create Date: 2026-07-07 13:06:15.607852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cbbdc5343a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('ai_text', sa.Text(), nullable=True),
    sa.Column('ai_prompt_used', sa.Text(), nullable=True),
    sa.Column('voice_used', sa.String(length=100), nullable=True),
    sa.Column('music_used', sa.String(length=255), nullable=True),
    sa.Column('bg_video_used', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='poststatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('video_path', sa.String(length=512), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=100), nullable=True),
    sa.Column('youtube_url', sa.String(length=512), nullable=True),
    sa.Column('youtube_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_source_id'), 'posts', ['source_id'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_auto_upload', sa.Boolean(), nullable=True),
    sa.Column('allowed_upload_start_time', sa.String(length=5), nullable=True),
    sa.Column('allowed_upload_end_time', sa.String(length=5), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_system_prompt', sa.Text(), nullable=True),
    sa.Column('default_voice_male', sa.String(length=100), nullable=True),
    sa.Column('default_voice_female', sa.String(length=100), nullable=True),
    sa.Column('font_style', sa.String(length=100), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('subtitle_outline', sa.Float(), nullable=True),
    sa.Column('youtube_privacy', sa.String(length=20), nullable=True),
    sa.Column('youtube_category_id', sa.String(length=10), nullable=True),
    sa.Column('youtube_tags', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_posts_source_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
