"""Add youtube metadata to Post

Revision ID: 3cc200cc14c7
Revises: 14cbbdc5343a
Create Date: 2026-07-07 20:46:37.232896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc200cc14c7'
down_revision: Union[str, Sequence[str], None] = '14cbbdc5343a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('youtube_title', sa.String(length=100), nullable=True))
    op.add_column('posts', sa.Column('youtube_description', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('youtube_tags', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'youtube_tags')
    op.drop_column('posts', 'youtube_description')
    op.drop_column('posts', 'youtube_title')
    # ### end Alembic commands ###
