"""refactor_settings_to_kv

Revision ID: 7ed65a996728
Revises: 3cc200cc14c7
Create Date: 2026-07-08 10:54:33.507604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ed65a996728'
down_revision: Union[str, Sequence[str], None] = '3cc200cc14c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('key', sa.String(length=100), nullable=False))
    op.add_column('settings', sa.Column('value', sa.Text(), nullable=False))
    op.add_column('settings', sa.Column('category', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.drop_column('settings', 'default_voice_female')
    op.drop_column('settings', 'ai_model')
    op.drop_column('settings', 'allowed_upload_end_time')
    op.drop_column('settings', 'allowed_upload_start_time')
    op.drop_column('settings', 'youtube_privacy')
    op.drop_column('settings', 'is_auto_upload')
    op.drop_column('settings', 'youtube_category_id')
    op.drop_column('settings', 'font_style')
    op.drop_column('settings', 'id')
    op.drop_column('settings', 'subtitle_outline')
    op.drop_column('settings', 'ai_provider')
    op.drop_column('settings', 'default_voice_male')
    op.drop_column('settings', 'font_size')
    op.drop_column('settings', 'ai_system_prompt')
    op.drop_column('settings', 'youtube_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('youtube_tags', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('settings', sa.Column('ai_system_prompt', mysql.TEXT(), nullable=True))
    op.add_column('settings', sa.Column('font_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('default_voice_male', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('settings', sa.Column('ai_provider', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('settings', sa.Column('subtitle_outline', mysql.FLOAT(), nullable=True))
    op.add_column('settings', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('settings', sa.Column('font_style', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('settings', sa.Column('youtube_category_id', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('settings', sa.Column('is_auto_upload', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('youtube_privacy', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('settings', sa.Column('allowed_upload_start_time', mysql.VARCHAR(length=5), nullable=True))
    op.add_column('settings', sa.Column('allowed_upload_end_time', mysql.VARCHAR(length=5), nullable=True))
    op.add_column('settings', sa.Column('ai_model', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('settings', sa.Column('default_voice_female', mysql.VARCHAR(length=100), nullable=True))
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.drop_column('settings', 'category')
    op.drop_column('settings', 'value')
    op.drop_column('settings', 'key')
    # ### end Alembic commands ###
